// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' 
show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-o4roRfHLOuS3uYrdb8BdbRMlT1kv8tI',
    appId: '1:16740347050:android:4936f221c6be1253c8b4d3',
    messagingSenderId: '16740347050',
    projectId: 'plant-watering-system-54df2',
    databaseURL: 'https://plant-watering-system-54df2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plant-watering-system-54df2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-o4roRfHLOuS3uYrdb8BdbRMlT1kv8tI',
    appId: '1:202596605948:ios:8cab58ac075f1974ae5c79',
    messagingSenderId: '16740347050',
    projectId: 'plant-watering-system-54df2',
    databaseURL: 'https://plant-watering-system-54df2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plant-watering-system-54df2.firebasestorage.app',
    iosBundleId: 'com.example.iotMicon',
  );

}